### ISSUE TITLE
Übersichtlichkeit

### ISSUE THREAD

**Issue by hansWURSCHT10000** [C0D3D3V/ITG-Klasse-13#3]
habe das alles etwas übersichtlicher gestaltet, sodass man das was man sucht schneller findet:
https://github.com/hansWURSCHT10000/ITG-Klasse-13_ENHANCED

**Comment by C0D3D3V** [comment]
Vielen Dank,
ich habe dein Vorschlag übernommen. Ich habe aber nicht das komplette Projekt verschmelzt weil mir aufgefallen ist das einige Dateien in deinem Projekt beschädigt sind. :(

**Comment by hansWURSCHT10000** [comment]
Was denn zB.?

Am 21. Oktober 2015 21:25:04 MESZ, schrieb C0D3D3V <notifications@github.com>:
